version: '3.7'
services:
  jupyterlab:
    # これだとJupyterのimageしか使えない
    # image: jupyter/datascience-notebook:latest
    # そのためDockerfileで合成したものを利用する
    build: ./docker/jupyterlab
    user: root
    environment:
      NB_UID: 1000
      NB_GID: 100
      GRANT_SUDO: "yes"
    volumes:
       - "./work:/home/jovyan/work"
    privileged: true
    ports:
      - "8888:8888"
    restart: unless-stopped
    command: start.sh jupyter lab --NotebookApp.token=''