version: "3"
services:
  jupyterlab:
    build: ./docker/jupyterlab
    user: root
    volumes:
#     - sharedir:/home/jovyan/work
        - C:\source\snippet\python:/home/JupyterLab/codes
    ports:
      - "18888:8888"
    environment:
      TZ: Asia/Tokyo
    command: 
      jupyter lab 
          --ip=0.0.0.0
          --allow-root
          --no-browser
          --NotebookApp.notebook_dir=/home/JupyterLab/codes
          --NotebookApp.token=password
# volumes:
#   sharedir:
#     driver_opts:
#       type: none
#       device: ./lab
#       o: bind
