FROM python:3
USER root
WORKDIR /usr/src/app
ENV DEBIAN_FRONTEND noninteractive

# 必要なパッケージを記載
RUN apt-get update && apt-get install --no-install-recommends -y \
    curl && \
    apt-get clean

# Jupyter Extensionのパッケージによっては必要なため
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs
RUN npm install npm@latest -g

# 必要なPythonパッケージを記載
RUN python -m pip install --upgrade pip && pip install \ 
    numpy \
    scipy \
    matplotlib \
    ipython \
    scikit-learn \
    pandas \
    pillow \
    mglearn \
    requests \
    pyperclip \
    beautifulsoup4 \
    jupyterlab \
    jupyterlab_code_formatter \
    ipywidgets \
    plotly \
    dash \
    dash-daq \
    dash-bio \
    dash-canvas \
    dash-auth \
    dash-cytoscape \
    jupyter-dash \
    xlrd

# プロキシ超え(別途docker-compose側から--build-argで与えてもらう想定)
#RUN npm config set proxy $http_proxy
#RUN npm config set https-proxy $https_proxy
#RUN npm config set registry https://registry.npmjs.org/

# JavaScriptを追加
RUN npm install -g ijavascript
RUN ijsinstall

# 必要なJupyterLab Extensionを記載
RUN jupyter labextension install @ryantam626/jupyterlab_code_formatter
RUN jupyter labextension install jupyterlab-plotly
# RUN jupyter labextension install jupyterlab_vim
# RUN jupyter labextension install jupyterlab-drawio
# RUN jupyter labextension install jupyterlab_tensorboard

RUN jupyter serverextension enable --py jupyterlab
RUN jupyter serverextension enable --py jupyterlab_code_formatter
# RUN jupyter serverextension enable --py jupyterlab_vim
# RUN jupyter serverextension enable --py jupyterlab-drawio
# RUN jupyter serverextension enable --py jupyterlab_tensorboard
ENV DEBIAN_FRONTEND dialog
